// Styles
import "../styles/globals.scss";
import { Inter } from "next/font/google";

import {
	ClerkProvider,
	SignedIn,
	SignedOut,
	RedirectToSignUp,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Uwallet",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<main>{children}</main>
				</body>
			</html>
		</ClerkProvider>

		// <ClerkProvider>
		//   <html lang="en">
		//     <body className={inter.className}>
		//       <main>
		//         <SignedIn>{children}</SignedIn>
		//         <SignedOut>
		//           <SingUpForm />
		//         </SignedOut>
		//       </main>
		//     </body>
		//   </html>
		// </ClerkProvider>
	);
}
