// Styles
import "../../styles/globals.scss";
import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { ViewProvider, TimeOutProvider } from "../context";

import Providers from "../utils/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Uwallet",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<ViewProvider>
				<TimeOutProvider>
				<html lang="en">
					<body className={inter.className}>
						<main>
							<Providers>{children}</Providers>
						</main>
					</body>
				</html>
				</TimeOutProvider>
			</ViewProvider>
		</ClerkProvider>
	);
}
